/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Interface.java to edit this template
 */
package pt.cjmach.jfrdp.lib;

/**
 *
 * @author mach
 */
public interface SettingsKeys {

    int getSetting();

    public static enum Bool implements SettingsKeys {
        SERVER_MODE(16),
        WAIT_FOR_OUTPUT_BUFFER_FLUSH(25),
        NETWORK_AUTO_DETECT(137),
        SUPPORT_ASYMETRIC_KEYS(138),
        SUPPORT_ERROR_INFO_PDU(139),
        SUPPORT_STATUS_INFO_PDU(140),
        SUPPORT_MONITOR_LAYOUT_PDU(141),
        SUPPORT_GRAPHICS_PIPELINE(142),
        SUPPORT_DYNAMIC_TIME_ZONE(143),
        SUPPORT_HEARTBEAT_PDU(144),
        SUPPORT_EDGE_ACTION_V1(150),
        SUPPORT_EDGE_ACTION_V2(151),
        SUPPORT_SKIP_CHANNEL_JOIN(152),
        USE_RDP_SECURITY_LAYER(192),
        SERVER_LICENSE_REQUIRED(202),
        CONSOLE_SESSION(322),
        SPAN_MONITORS(387),
        USE_MULTIMON(388),
        FORCE_MULTIMON(389),
        LIST_MONITORS(392),
        HAS_MONITOR_ATTRIBUTES(397),
        SUPPORT_MULTITRANSPORT(513),
        AUTO_LOGON_ENABLED(704),
        COMPRESSION_ENABLED(705),
        DISABLE_CTRL_ALT_DEL(706),
        ENABLE_WINDOWS_KEY(707),
        MAXIMIZE_SHELL(708),
        LOGON_NOTIFY(709),
        LOGON_ERRORS(710),
        MOUSE_ATTACHED(711),
        MOUSE_HAS_WHEEL(712),
        REMOTE_CONSOLE_AUDIO(713),
        AUDIO_PLAYBACK(714),
        AUDIO_CAPTURE(715),
        VIDEO_DISABLE(716),
        PASSWORD_IS_SMARTCARD_PIN(717),
        USING_SAVED_CREDENTIALS(718),
        FORCE_ENCRYPTED_CS_PDU(719),
        HI_DEF_REMOTE_APP(720),
        IPV6_ENABLED(768),
        AUTO_RECONNECTION_ENABLED(832),
        PRINT_RECONNECT_COOKIE(836),
        AUTO_RECONNECTION_PACKET_SUPPORTED(837),
        DYNAMIC_DAYLIGHT_TIME_DISABLED(898),
        ALLOW_FONT_SMOOTHING(961),
        DISABLE_WALLPAPER(962),
        DISABLE_FULL_WINDOW_DRAG(963),
        DISABLE_MENU_ANIMS(964),
        DISABLE_THEMES(965),
        DISABLE_CURSOR_SHADOW(966),
        DISABLE_CURSOR_BLINKING(967),
        ALLOW_DESKTOP_COMPOSITION(968),
        REMOTE_ASSISTANCE_MODE(1024),
        ENCOMSP_VIRTUAL_CHANNEL(1029),
        REMDESK_VIRTUAL_CHANNEL(1030),
        LYNC_RDP_MODE(1031),
        REMOTE_ASSISTANCE_REQUEST_CONTROL(1032),
        TLS_SECURITY(1088),
        NLA_SECURITY(1089),
        RDP_SECURITY(1090),
        EXT_SECURITY(1091),
        AUTHENTICATION(1092),
        NEGOTIATE_SECURITY_LAYER(1096),
        RESTRICTED_ADMIN_MODE_REQUIRED(1097),
        DISABLE_CREDENTIALS_DELEGATION(1099),
        VM_CONNECT_MODE(1102),
        FIPS_MODE(1104),
        RDSTLS_SECURITY(1111),
        AAD_SECURITY(1112),
        REMOTE_CREDENTIAL_GUARD(1114),
        MSTSC_COOKIE_MODE(1152),
        SEND_PRECONNECTION_PDU(1156),
        SMARTCARD_LOGON(1282),
        PROMPT_FOR_CREDENTIALS(1283),
        SMARTCARD_EMULATION(1288),
        KERBEROS_RDG_IS_PROXY(1352),
        IGNORE_CERTIFICATE(1408),
        EXTERNAL_CERTIFICATE_MANAGEMENT(1415),
        AUTO_ACCEPT_CERTIFICATE(1419),
        AUTO_DENY_CERTIFICATE(1420),
        CERTIFICATE_CALLBACK_PREFER_PEM(1423),
        WORKAREA(1536),
        FULLSCREEN(1537),
        GRAB_KEYBOARD(1539),
        DECORATIONS(1540),
        MOUSE_MOTION(1541),
        ASYNC_UPDATE(1545),
        ASYNC_CHANNELS(1546),
        TOGGLE_FULLSCREEN(1548),
        EMBEDDED_WINDOW(1550),
        SMART_SIZING(1551),
        PERCENT_SCREEN_USE_WIDTH(1556),
        PERCENT_SCREEN_USE_HEIGHT(1557),
        DYNAMIC_RESOLUTION_UPDATE(1558),
        GRAB_MOUSE(1559),
        SOFTWARE_GDI(1601),
        LOCAL_CONNECTION(1602),
        AUTHENTICATION_ONLY(1603),
        CREDENTIALS_FROM_STDIN(1604),
        UNMAP_BUTTONS(1605),
        OLD_LICENSE_BEHAVIOUR(1606),
        MOUSE_USE_RELATIVE_MOVE(1607),
        USE_COMMON_STDIO_CALLBACKS(1608),
        CONNECT_CHILD_SESSION(1609),
        DUMP_REMOTE_FX(1856),
        PLAY_REMOTE_FX(1857),
        TRANSPORT_DUMP(1860),
        TRANSPORT_DUMP_REPLAY(1862),
        DEACTIVATE_CLIENT_DECODING(1863),
        TRANSPORT_DUMP_REPLAY_NODELAY(1864),
        GATEWAY_USE_SAME_CREDENTIALS(1991),
        GATEWAY_ENABLED(1992),
        GATEWAY_BYPASS_LOCAL(1993),
        GATEWAY_RPC_TRANSPORT(1994),
        GATEWAY_HTTP_TRANSPORT(1995),
        GATEWAY_UDP_TRANSPORT(1996),
        GATEWAY_HTTP_USE_WEBSOCKETS(2000),
        GATEWAY_HTTP_EXT_AUTH_SSPI_NTLM(2001),
        GATEWAY_ARM_TRANSPORT(2004),
        GATEWAY_IGNORE_REDIRECTION_POLICY(2012),
        GATEWAY_AVD_USE_TENANTID(2020),
        REMOTE_APPLICATION_MODE(2112),
        DISABLE_REMOTE_APP_CAPS_CHECK(2121),
        REMOTE_APP_LANGUAGE_BAR_SUPPORTED(2124),
        REFRESH_RECT(2306),
        SUPPRESS_OUTPUT(2307),
        FAST_PATH_OUTPUT(2308),
        SALTED_CHECKSUM(2309),
        LONG_CREDENTIALS_SUPPORTED(2310),
        NO_BITMAP_COMPRESSION_HEADER(2311),
        BITMAP_COMPRESSION_DISABLED(2312),
        DESKTOP_RESIZE(2368),
        DRAW_ALLOW_DYNAMIC_COLOR_FIDELITY(2369),
        DRAW_ALLOW_COLOR_SUBSAMPLING(2370),
        DRAW_ALLOW_SKIPALPHA(2371),
        BITMAP_CACHEV3_ENABLED(2433),
        ALT_SEC_FRAME_MARKER_SUPPORT(2434),
        ALLOW_UNANOUNCED_ORDERS_FROM_SERVER(2435),
        BITMAP_CACHE_ENABLED(2497),
        ALLOW_CACHE_WAITING_LIST(2499),
        BITMAP_CACHE_PERSIST_ENABLED(2500),
        UNICODE_INPUT(2629),
        FAST_PATH_INPUT(2630),
        MULTI_TOUCH_INPUT(2631),
        MULTI_TOUCH_GESTURES(2632),
        HAS_HORIZONTAL_WHEEL(2634),
        HAS_EXTENDED_MOUSE_EVENT(2635),
        SUSPEND_INPUT(2636),
        HAS_RELATIVE_MOUSE_EVENT(2638),
        HAS_QOE_EVENT(2639),
        SOUND_BEEPS_ENABLED(2944),
        SURFACE_COMMANDS_ENABLED(3520),
        FRAME_MARKER_COMMAND_ENABLED(3521),
        SURFACE_FRAME_MARKER_ENABLED(3522),
        REMOTE_FX_ONLY(3648),
        REMOTE_FX_CODEC(3649),
        REMOTE_FX_IMAGE_CODEC(3652),
        NSCODEC(3712),
        NSCODEC_ALLOW_SUBSAMPLING(3716),
        NSCODEC_ALLOW_DYNAMIC_COLOR_FIDELITY(3717),
        JPEG_CODEC(3776),
        GFX_THIN_CLIENT(3840),
        GFX_SMALL_CACHE(3841),
        GFX_PROGRESSIVE(3842),
        GFX_PROGRESSIVEV2(3843),
        GFX_H264(3844),
        GFX_AVC444(3845),
        GFX_SEND_QOE_ACK(3846),
        GFX_AVC444V2(3847),
        GFX_PLANAR(3849),
        GFX_SUSPEND_FRAME_ACK(3850),
        DRAW_NINE_GRID_ENABLED(3968),
        DRAW_GDI_PLUS_ENABLED(4032),
        DRAW_GDI_PLUS_CACHE_ENABLED(4033),
        DEVICE_REDIRECTION(4160),
        IGNORE_INVALID_DEVICES(4164),
        REDIRECT_DRIVES(4288),
        REDIRECT_HOME_DRIVE(4289),
        REDIRECT_SMART_CARDS(4416),
        REDIRECT_WEB_AUTHN(4417),
        REDIRECT_PRINTERS(4544),
        REDIRECT_SERIAL_PORTS(4672),
        REDIRECT_PARALLEL_PORTS(4673),
        PREFER_IPV6_OVER_IPV4(4674),
        REDIRECT_CLIPBOARD(4800),
        SYNCHRONOUS_STATIC_CHANNELS(4931),
        SUPPORT_DYNAMIC_CHANNELS(5059),
        SYNCHRONOUS_DYNAMIC_CHANNELS(5060),
        SUPPORT_ECHO_CHANNEL(5184),
        SUPPORT_DISPLAY_CONTROL(5185),
        SUPPORT_GEOMETRY_TRACKING(5186),
        SUPPORT_SSHAGENT_CHANNEL(5187),
        SUPPORT_VIDEO_OPTIMIZED(5188),
        TCP_KEEP_ALIVE(5190),
        UNUSED(-1);

        private final int setting;

        private Bool(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }

    public static enum Int16 implements SettingsKeys {
        UNUSED(-1);

        private final int setting;

        private Int16(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }

    public static enum Int32 implements SettingsKeys {
        MONITOR_LOCAL_SHIFT_X(395),
        MONITOR_LOCAL_SHIFT_Y(396),
        X_PAN(1552),
        Y_PAN(1553),
        UNUSED(-1);

        private final int setting;

        private Int32(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }

    public static enum Int64 implements SettingsKeys {
        UNUSED(-1);

        private final int setting;

        private Int64(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }

    public static enum Pointer implements SettingsKeys {
        INSTANCE(0),
        SERVER_RANDOM(196),
        SERVER_CERTIFICATE(198),
        CLIENT_RANDOM(200),
        SERVER_LICENSE_PRODUCT_ISSUERS(206),
        CHANNEL_DEF_ARRAY(258),
        MONITOR_DEF_ARRAY(386),
        MONITOR_IDS(393),
        CLIENT_AUTO_RECONNECT_COOKIE(834),
        SERVER_AUTO_RECONNECT_COOKIE(835),
        CLIENT_TIME_ZONE(896),
        LOAD_BALANCE_INFO(1218),
        REDIRECTION_PASSWORD(1222),
        REDIRECTION_TSV_URL(1226),
        TARGET_NET_ADDRESSES(1229),
        TARGET_NET_PORTS(1230),
        REDIRECTION_GUID(1234),
        REDIRECTION_TARGET_CERTIFICATE(1236),
        PASSWORD51(1280),
        RDP_SERVER_RSA_KEY(1413),
        RDP_SERVER_CERTIFICATE(1414),
        RECEIVED_CAPABILITIES(2240),
        RECEIVED_CAPABILITY_DATA(2242),
        RECEIVED_CAPABILITY_DATA_SIZES(2243),
        ORDER_SUPPORT(2432),
        BITMAP_CACHEV2_CELL_INFO(2502),
        GLYPH_CACHE(2753),
        FRAG_CACHE(2754),
        DEVICE_ARRAY(4163),
        STATIC_CHANNEL_ARRAY(4930),
        DYNAMIC_CHANNEL_ARRAY(5058),
        UNUSED(-1);

        private final int setting;

        private Pointer(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }

    public static enum String implements SettingsKeys {
        SERVER_HOSTNAME(20),
        USERNAME(21),
        PASSWORD(22),
        DOMAIN(23),
        PASSWORD_HASH(24),
        ACCEPTED_CERT(27),
        USER_SPECIFIED_SERVER_NAME(29),
        AAD_SERVER_HOSTNAME(30),
        CLIENT_HOSTNAME(134),
        CLIENT_PRODUCTID(135),
        SERVER_LICENSE_COMPANY_NAME(203),
        SERVER_LICENSE_PRODUCT_NAME(205),
        ALTERNATE_SHELL(640),
        SHELL_WORKING_DIRECTORY(641),
        CLIENT_ADDRESS(769),
        CLIENT_DIR(770),
        DYNAMIC_DST_TIME_ZONE_KEY_NAME(897),
        REMOTE_ASSISTANCE_SESSION_ID(1025),
        REMOTE_ASSISTANCE_PASS_STUB(1026),
        REMOTE_ASSISTANCE_PASSWORD(1027),
        REMOTE_ASSISTANCE_RCTICKET(1028),
        AUTHENTICATION_SERVICE_CLASS(1098),
        ALLOWED_TLS_CIPHERS(1101),
        NTLM_SAM_FILE(1103),
        SSPI_MODULE(1106),
        TLS_SECRETS_FILE(1109),
        AUTHENTICATION_PACKAGE_LIST(1110),
        WIN_SCARD_MODULE(1113),
        PRECONNECTION_BLOB(1155),
        TARGET_NET_ADDRESS(1217),
        REDIRECTION_USERNAME(1220),
        REDIRECTION_DOMAIN(1221),
        REDIRECTION_TARGET_FQDN(1224),
        REDIRECTION_TARGET_NET_BIOS_NAME(1225),
        REDIRECTION_ACCEPTED_CERT(1231),
        SMARTCARD_CERTIFICATE(1285),
        SMARTCARD_PRIVATE_KEY(1286),
        PKCS11_MODULE(1289),
        PKINIT_ANCHORS(1290),
        CARD_NAME(1292),
        READER_NAME(1293),
        CONTAINER_NAME(1294),
        CSP_NAME(1295),
        KERBEROS_KDC_URL(1344),
        KERBEROS_REALM(1345),
        KERBEROS_START_TIME(1346),
        KERBEROS_LIFE_TIME(1347),
        KERBEROS_RENEWABLE_LIFE_TIME(1348),
        KERBEROS_CACHE(1349),
        KERBEROS_ARMOR(1350),
        KERBEROS_KEYTAB(1351),
        CERTIFICATE_NAME(1409),
        CERTIFICATE_ACCEPTED_FINGERPRINTS(1421),
        WINDOW_TITLE(1542),
        WM_CLASS(1549),
        COMPUTER_NAME(1664),
        CONNECTION_FILE(1728),
        ASSISTANCE_FILE(1729),
        HOME_PATH(1792),
        CONFIG_PATH(1793),
        CURRENT_PATH(1794),
        DUMP_REMOTE_FX_FILE(1858),
        PLAY_REMOTE_FX_FILE(1859),
        TRANSPORT_DUMP_FILE(1861),
        GATEWAY_HOSTNAME(1986),
        GATEWAY_USERNAME(1987),
        GATEWAY_PASSWORD(1988),
        GATEWAY_DOMAIN(1989),
        GATEWAY_ACCESS_TOKEN(1997),
        GATEWAY_ACCEPTED_CERT(1998),
        GATEWAY_HTTP_EXT_AUTH_BEARER(2002),
        GATEWAY_URL(2003),
        GATEWAY_AVD_WVD_ENDPOINT_POOL(2005),
        GATEWAY_AVD_GEO(2006),
        GATEWAY_AVD_ARMPATH(2007),
        GATEWAY_AVD_AADTENANTID(2008),
        GATEWAY_AVD_DIAGNOSTICSERVICEURL(2009),
        GATEWAY_AVD_HUBDISCOVERYGEOURL(2010),
        GATEWAY_AVD_ACTIVITY_HINT(2011),
        GATEWAY_AVD_CLIENT_ID(2013),
        GATEWAY_AZURE_ACTIVE_DIRECTORY(2014),
        PROXY_HOSTNAME(2016),
        PROXY_USERNAME(2018),
        PROXY_PASSWORD(2019),
        REMOTE_APPLICATION_NAME(2113),
        REMOTE_APPLICATION_ICON(2114),
        REMOTE_APPLICATION_PROGRAM(2115),
        REMOTE_APPLICATION_FILE(2116),
        REMOTE_APPLICATION_GUID(2117),
        REMOTE_APPLICATION_CMDLINE(2118),
        REMOTE_APPLICATION_WORKING_DIR(2128),
        TERMINAL_DESCRIPTOR(2438),
        BITMAP_CACHE_PERSIST_FILE(2503),
        KEYBOARD_REMAPPING_LIST(2622),
        IME_FILE_NAME(2628),
        KEYBOARD_PIPE_NAME(2637),
        DRIVES_TO_REDIRECT(4290),
        CLIPBOARD_USE_SELECTION(4802),
        RDP2TCP_ARGS(5189),
        ACTION_SCRIPT(5195),
        UNUSED(-1);

        private final int setting;

        private String(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }

    public static enum UInt16 implements SettingsKeys {
        DESKTOP_ORIENTATION(147),
        SUPPORTED_COLOR_DEPTHS(153),
        TLS_MIN_VERSION(1107),
        TLS_MAX_VERSION(1108),
        PROXY_PORT(2017),
        CAPS_PROTOCOL_VERSION(2313),
        CAPS_GENERAL_COMPRESSION_TYPES(2314),
        CAPS_UPDATE_CAPABILITY_FLAG(2315),
        CAPS_REMOTE_UNSHARE_FLAG(2316),
        CAPS_GENERAL_COMPRESSION_LEVEL(2317),
        ORDER_SUPPORT_FLAGS(2436),
        ORDER_SUPPORT_FLAGS_EX(2437),
        TEXT_ANSI_CODE_PAGE(2439),
        UNUSED(-1);

        private final int setting;

        private UInt16(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }

    public static enum UInt32 implements SettingsKeys {
        SHARE_ID(17),
        PDU_SOURCE(18),
        SERVER_PORT(19),
        ACCEPTED_CERT_LENGTH(28),
        THREADING_FLAGS(64),
        RDP_VERSION(128),
        DESKTOP_WIDTH(129),
        DESKTOP_HEIGHT(130),
        COLOR_DEPTH(131),
        CONNECTION_TYPE(132),
        CLIENT_BUILD(133),
        EARLY_CAPABILITY_FLAGS(136),
        DESKTOP_PHYSICAL_WIDTH(145),
        DESKTOP_PHYSICAL_HEIGHT(146),
        DESKTOP_SCALE_FACTOR(148),
        DEVICE_SCALE_FACTOR(149),
        ENCRYPTION_METHODS(193),
        EXT_ENCRYPTION_METHODS(194),
        ENCRYPTION_LEVEL(195),
        SERVER_RANDOM_LENGTH(197),
        SERVER_CERTIFICATE_LENGTH(199),
        CLIENT_RANDOM_LENGTH(201),
        SERVER_LICENSE_PRODUCT_VERSION(204),
        SERVER_LICENSE_PRODUCT_ISSUERS_COUNT(207),
        CHANNEL_COUNT(256),
        CHANNEL_DEF_ARRAY_SIZE(257),
        CLUSTER_INFO_FLAGS(320),
        REDIRECTED_SESSION_ID(321),
        MONITOR_COUNT(384),
        MONITOR_DEF_ARRAY_SIZE(385),
        DESKTOP_POS_X(390),
        DESKTOP_POS_Y(391),
        NUM_MONITOR_IDS(394),
        MONITOR_FLAGS(398),
        MONITOR_ATTRIBUTE_FLAGS(399),
        MULTITRANSPORT_FLAGS(512),
        COMPRESSION_LEVEL(721),
        CLIENT_SESSION_ID(771),
        AUTO_RECONNECT_MAX_RETRIES(833),
        PERFORMANCE_FLAGS(960),
        REQUESTED_PROTOCOLS(1093),
        SELECTED_PROTOCOL(1094),
        NEGOTIATION_FLAGS(1095),
        AUTHENTICATION_LEVEL(1100),
        TLS_SEC_LEVEL(1105),
        COOKIE_MAX_LENGTH(1153),
        PRECONNECTION_ID(1154),
        REDIRECTION_FLAGS(1216),
        LOAD_BALANCE_INFO_LENGTH(1219),
        REDIRECTION_PASSWORD_LENGTH(1223),
        REDIRECTION_TSV_URL_LENGTH(1227),
        TARGET_NET_ADDRESS_COUNT(1228),
        REDIRECTION_ACCEPTED_CERT_LENGTH(1232),
        REDIRECTION_PREFER_TYPE(1233),
        REDIRECTION_GUID_LENGTH(1235),
        PASSWORD51_LENGTH(1281),
        KEY_SPEC(1291),
        PERCENT_SCREEN(1538),
        SMART_SIZING_WIDTH(1554),
        SMART_SIZING_HEIGHT(1555),
        GATEWAY_USAGE_METHOD(1984),
        GATEWAY_PORT(1985),
        GATEWAY_CREDENTIALS_SOURCE(1990),
        GATEWAY_ACCEPTED_CERT_LENGTH(1999),
        PROXY_TYPE(2015),
        REMOTE_APPLICATION_EXPAND_CMDLINE(2119),
        REMOTE_APPLICATION_EXPAND_WORKING_DIR(2120),
        REMOTE_APP_NUM_ICON_CACHES(2122),
        REMOTE_APP_NUM_ICON_CACHE_ENTRIES(2123),
        REMOTE_WND_SUPPORT_LEVEL(2125),
        REMOTE_APPLICATION_SUPPORT_LEVEL(2126),
        REMOTE_APPLICATION_SUPPORT_MASK(2127),
        RECEIVED_CAPABILITIES_SIZE(2241),
        OS_MAJOR_TYPE(2304),
        OS_MINOR_TYPE(2305),
        BITMAP_CACHE_VERSION(2498),
        BITMAP_CACHEV2_NUM_CELLS(2501),
        COLOR_POINTER_CACHE_SIZE(2560),
        POINTER_CACHE_SIZE(2561),
        KEYBOARD_CODE_PAGE(2623),
        KEYBOARD_LAYOUT(2624),
        KEYBOARD_TYPE(2625),
        KEYBOARD_SUB_TYPE(2626),
        KEYBOARD_FUNCTION_KEY(2627),
        KEYBOARD_HOOK(2633),
        BRUSH_SUPPORT_LEVEL(2688),
        GLYPH_SUPPORT_LEVEL(2752),
        OFFSCREEN_SUPPORT_LEVEL(2816),
        OFFSCREEN_CACHE_SIZE(2817),
        OFFSCREEN_CACHE_ENTRIES(2818),
        VC_FLAGS(2880),
        VC_CHUNK_SIZE(2881),
        MULTIFRAG_MAX_REQUEST_SIZE(3328),
        LARGE_POINTER_FLAG(3392),
        COMP_DESK_SUPPORT_LEVEL(3456),
        SURFACE_COMMANDS_SUPPORTED(3523),
        REMOTE_FX_CODEC_ID(3650),
        REMOTE_FX_CODEC_MODE(3651),
        REMOTE_FX_CAPTURE_FLAGS(3653),
        REMOTE_FX_RLGR_MODE(3654),
        NSCODEC_ID(3713),
        FRAME_ACKNOWLEDGE(3714),
        NSCODEC_COLOR_LOSS_LEVEL(3715),
        JPEG_CODEC_ID(3777),
        JPEG_QUALITY(3778),
        GFX_CAPS_FILTER(3848),
        BITMAP_CACHEV3_CODEC_ID(3904),
        DRAW_NINE_GRID_CACHE_SIZE(3969),
        DRAW_NINE_GRID_CACHE_ENTRIES(3970),
        DEVICE_COUNT(4161),
        DEVICE_ARRAY_SIZE(4162),
        FORCE_IPVX(4675),
        CLIPBOARD_FEATURE_MASK(4801),
        STATIC_CHANNEL_COUNT(4928),
        STATIC_CHANNEL_ARRAY_SIZE(4929),
        DYNAMIC_CHANNEL_COUNT(5056),
        DYNAMIC_CHANNEL_ARRAY_SIZE(5057),
        TCP_KEEP_ALIVE_RETRIES(5191),
        TCP_KEEP_ALIVE_DELAY(5192),
        TCP_KEEP_ALIVE_INTERVAL(5193),
        TCP_ACK_TIMEOUT(5194),
        FLOATBAR(5196),
        TCP_CONNECT_TIMEOUT(5197),
        FAKE_MOUSE_MOTION_INTERVAL(5198),
        UNUSED(-1);

        private final int setting;

        private UInt32(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }

    public enum UInt64 implements SettingsKeys {
        PARENT_WINDOW_ID(1543),
        UNUSED(-1);

        private final int setting;

        private UInt64(int setting) {
            this.setting = setting;
        }

        @Override
        public int getSetting() {
            return setting;
        }
    }
}
