/*
 * Licensed to the Apache Software Foundation (ASF) under one or more 
 * contributor license agreements.  See the NOTICE file distributed with this 
 * work for additional information regarding copyright ownership. The ASF 
 * licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License.  
 * You may obtain a copy of the License at
 * 
 *   https://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the 
 * License for the specific language governing permissions and limitations
 * under the License.  
 */
package pt.cjmach.jfrdp.client;

/**
 *
 * @author cmachado
 */
public class ConnectPanel extends javax.swing.JPanel {

    /**
     * Creates new form ConnectPanel
     */
    public ConnectPanel() {
        initComponents();
    }
    
    public String getDomain() {
        return textFieldDomain.getText();
    }
    
    public char[] getPassword() {
        return textFieldPassword.getPassword();
    }
    
    public String getServer() {
        return textFieldServer.getText();
    }
    
    public String getUser() {
        return textFieldUser.getText();
    }
    
    public void focusFirstTextField() {
        textFieldServer.requestFocusInWindow();
    }
    
    public void reset() {
        textFieldServer.setText("");
        textFieldDomain.setText("");
        textFieldUser.setText("");
        textFieldPassword.setText("");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelServer = new javax.swing.JLabel();
        textFieldServer = new javax.swing.JTextField();
        labelDomain = new javax.swing.JLabel();
        textFieldDomain = new javax.swing.JTextField();
        labelUser = new javax.swing.JLabel();
        textFieldUser = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        textFieldPassword = new javax.swing.JPasswordField();

        labelServer.setLabelFor(textFieldServer);
        labelServer.setText("Server:");
        labelServer.setFocusable(false);
        labelServer.setRequestFocusEnabled(false);

        labelDomain.setLabelFor(textFieldDomain);
        labelDomain.setText("Domain:");
        labelDomain.setFocusable(false);
        labelDomain.setRequestFocusEnabled(false);

        labelUser.setLabelFor(textFieldUser);
        labelUser.setText("User:");
        labelUser.setFocusable(false);
        labelUser.setRequestFocusEnabled(false);

        labelPassword.setLabelFor(textFieldPassword);
        labelPassword.setText("Password:");
        labelPassword.setFocusable(false);
        labelPassword.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPassword)
                    .addComponent(labelUser)
                    .addComponent(labelDomain)
                    .addComponent(labelServer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldServer)
                    .addComponent(textFieldDomain)
                    .addComponent(textFieldUser)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServer)
                    .addComponent(textFieldServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDomain)
                    .addComponent(textFieldDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUser)
                    .addComponent(textFieldUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelDomain;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelServer;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTextField textFieldDomain;
    private javax.swing.JPasswordField textFieldPassword;
    private javax.swing.JTextField textFieldServer;
    private javax.swing.JTextField textFieldUser;
    // End of variables declaration//GEN-END:variables
}
